language: ruby
rvm:
  - ruby-head
  - 2.1.0
  - 1.9.3
  - jruby-head
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-2.1.1
  - 1.8.7
  - ree
matrix:
  allow_failures:
    - rvm: jruby-head
branch:
  only:
    - master
    - /^release-.*$/
